apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        imagePullPolicy: IfNotPresent
        image: heroku/nodejs-hello-world
        ports:
        - containerPort: 3000