apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  ports:
  - name: hello-app
    port: 3000
    targetPort: 3000
  clusterIP: None
  selector:
    app: hello-app