apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        imagePullPolicy: Never
        image: ismail/hello-app:1.0.1
        ports:
        - containerPort: 3000